variable "kafka_version" {}
variable "broker_count" {}
variable "kafka_instance_type" {}
variable "kafka_ebs_volume_size" {}
variable "subnet_ids" {}
variable "client_tls_auth_enabled" {}
variable "client_sasl_scram_enabled" {}
variable "client_sasl_iam_enabled" {}
variable "enhanced_monitoring" {}
variable "jmx_exporter_enabled" {}
variable "node_exporter_enabled" {}
variable "kafka_properties" {}
variable "cloudwatch_logs_enabled" {}
variable "s3_logs_enabled" {}
variable "security_group_id" {}
variable "msk_logs_bucket" {}
variable "cloudwatch_log_group_name" {}
variable "certificate_authority_arn" {}
variable "msk_custom_config" {}
variable "msk_secret_arn" {}